apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /root
      name: emptydir
  - name: busybox
    image: busybox
    args:
      - /bin/sh
      - -c
      - date > /root/date.txt
    volumeMounts:
    - mountPath: /root
      name: emptydir
  volumes:
  - name: emptydir
    emptyDir: {}
