apiVersion: v1
kind: PersistentVolume
metadata:
  name: myclass
  labels:
    name: myclass
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data
    type: Directory
